AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  LearningRoadmapGenerator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 180
      Events:
        Handle:
          Type: Api
          Properties:
            Path: /handle
            Method: POST
        Request:
          Type: Api
          Properties:
            Path: /request
            Method: POST
      Environment:
        Variables:
          EXEC_LOCAL: false
          LINE_CHANNEL_ACCESS_TOKEN: token
          LINE_CHANNEL_SECRET: secret
          LIFF_URL: https://liff.line.me/1660932490-KmOXp0BL
          FRONTEND_ORIGIN_URL: https://learning-roadmap-generator.web.app
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/index.ts
