AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  LearningRoadmapGenerator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./handler
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 180
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /handle
            Method: POST
      Environment:
        Variables:
          EXEC_LOCAL: false
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/index.ts
